### ISSUE TITLE
Vest - Can't Vest Sponsor Fee.

### ISSUE THREAD

**Issue by jose-garrofe** [AelinXYZ/aelin-frontend-v2#366]
![image (5).png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/04e0cf04-e76b-4c44-9575-06f5e940183c)

**Description:**
When accessing a pool as a Sponsor after de Vesting Period ended, I can't vest my tokens for the Sponsor Fee.

**Steps to reproduce:**
- Create a Pool.
- Have other people invest in it.
- Create a Deal.
- Holder must fund the deal.
- Investors must accept the deal.
- After vesting period ended, connect your sponsor wallet and enter the pool.

**Actual Result:**
On the Vest section the following message is displayed: 'All your deals tokens have been vested
Total Vested: undefined undefined'

**Expected Result:**
User should see the ammount of tokens corresponding the sponsor fee with the vest option to claim them.

**Comment by 0xlinus** [comment]
@saeta-eth this is fixed by your PR right?

**Comment by saeta-eth** [comment]
Yes, it should be fixed now. https://github.com/AelinXYZ/aelin-frontend-v2/pull/397
