### ISSUE TITLE
Release funds pool Sponsor/Counter-party notice

### ISSUE THREAD

**Issue by InakyMaister** [AelinXYZ/aelin-frontend-v2#386]
- [ ] When a Sponsor is cancelling a pool/releasing the investors funds, the Sponsor becomes the Counter party for the 30 minutes of "Cooldown" period before the cancelling/release takes place. The UI should inform the Sponsor, now also counter-party to not fund the deal.

Such as the next Figma design screen:

https://www.figma.com/file/ZBGhsSy6bQOB6XxNHSlBiF/V2?node-id=1095%3A48309

Rewording suggestion: _We noticed you are the sponsor and the counter party. This is usually due to a pool cancellation unless you are funding your own deal. If you wish to cancel the pool no further action is required_

**Comment by 0xlinus** [comment]
Duplicate #465
