### ISSUE TITLE
Aelin price chart

### ISSUE THREAD

**Issue by 0xlinus** [AelinXYZ/aelin-frontend-v2#400]
Increase price chart time frame otherwise it will look flat (and potentially misleading) all the time
![image](https://user-images.githubusercontent.com/99757679/171495704-2b878f0b-d381-465a-b799-a3093d367f97.png)

**Comment by saeta-eth** [comment]
@0xlinus This was discussed previously and 1d was the selected time period. In my opinion, we can improve this section of the sidebar by adding a dropdown menu with different time periods and letting users decide what they want to see.

cc: @0xDmitry @alextheboredape
