### ISSUE TITLE
All Token Vested should be deleted if the investor claimed all tokens

### ISSUE THREAD

**Issue by 0xlinus** [AelinXYZ/aelin-frontend-v2#429]

**Comment by saeta-eth** [comment]
Remaining tokens is not 0, that is why it's not showing the correct vesting screen

<img width="883" alt="Screen Shot 2022-06-02 at 20 21 21" src="https://user-images.githubusercontent.com/15804684/171753691-6e52c69c-7d47-4d3e-a12a-8eb762c7bd38.png">

**Comment by 0xlinus** [comment]
> RemainingAmountToVest is not 0, that is why it's not showing the correct vesting screen
> 
> <img alt="Screen Shot 2022-06-02 at 20 21 21" width="883" src="https://user-images.githubusercontent.com/15804684/171753691-6e52c69c-7d47-4d3e-a12a-8eb762c7bd38.png">

This is Subgraph task to delete a notification. Are you sure this is related to what you've mentioned?

**Comment by saeta-eth** [comment]
Yes, they are all related.

I've been thinking how to fix this. One option could be to add a timestamp when the user claims their tokens. If the `timestamp > vestingPeriod`, we can assume that the user has already claimed everything.
