### ISSUE TITLE
Vest should be disabled if amount to vest is 0

### ISSUE THREAD

**Issue by 0xlinus** [AelinXYZ/aelin-frontend-v2#435]
![image](https://user-images.githubusercontent.com/99757679/171757634-d73045e2-02f3-47b1-995d-d0cba81665e2.png)

**Comment by saeta-eth** [comment]
This is the same issue as https://github.com/AelinXYZ/aelin-frontend-v2/issues/429. The problem is that the subgraph sometimes returns `remainingAmountToVest > 0` when all the deal tokens were already claimed.

**Comment by saeta-eth** [comment]
Going to close this because we already have a ticket for this.
