### ISSUE TITLE
Add red text if Round2 not available 

### ISSUE THREAD

**Issue by 0xlinus** [AelinXYZ/aelin-frontend-v2#475]

**Comment by saeta-eth** [comment]
It's fixed on this PR: https://github.com/AelinXYZ/aelin-frontend-v2/pull/419

<img width="734" alt="Screen Shot 2022-06-09 at 11 57 13" src="https://user-images.githubusercontent.com/15804684/172878240-2bad7660-d8b0-4331-af77-d2a2034ddc95.png">
