### ISSUE TITLE
AELIP-15: Avoid flickering effect on Tabs content

### ISSUE THREAD

**Issue by saeta-eth** [AelinXYZ/aelin-frontend-v2#568]
I think the tabs and their content should be the same width to avoid this flickering effect

https://user-images.githubusercontent.com/15804684/177810003-5c483a94-a1b2-45dd-bbc7-3030c1af8ee1.mov

**Comment by 0xlinus** [comment]
@saeta-eth but since you can add multiple collections that container's height is dynamic.
I'd leave it that way

https://user-images.githubusercontent.com/99757679/183489618-da4546b6-f196-4cdc-a4a0-011e1b4471cb.mp4
