### ISSUE TITLE
"Pools vouched by" input doesn't cleared after click on the "Aelin" home button

### ISSUE THREAD

**Issue by 0xDmitry** [AelinXYZ/aelin-frontend-v2#959]
When user clicks on the "Aelin" home button we need to clear "Pools vouched by" input

<img width="1792" alt="Screenshot 2023-02-28 at 20 37 57" src="https://user-images.githubusercontent.com/61683409/221934275-076d0d81-9429-400f-be0e-45b15498f71d.png">

**Comment by 0xlinus** [comment]
Do we want to be cleared?

**Comment by 0xDmitry** [comment]
> Do we want to be cleared?

That's a good question actually. But anyway we want to input and table be synchronised, that's the main issue I guess.
